# Site settings
title: 周鹏的技术博客
email: zhou437383092@163.com
description: > #周鹏的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://zhoupIT.github.io/ITBlog/" # the base hostname & protocol for your site
github_username:  zhoupIT

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 周鹏
  email: zhou437383092@163.com
  weibo: http://weibo.com/2151268355/profile?topnav=1&wvr=6&is_all=1
  github: http://github.com/zhoupIT
title: 周鹏的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: http://upload-images.jianshu.io/upload_images/1041928-dc6bb7346f4c7d7c.JPG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

# ba:
#   src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: zhoupIT
